# 端口
server:
  port: 8080
  name: es-service
  servlet:
    context-path: /

# 多环境配置
spring:
  application:
    name: ${server.name}
  profiles:
    active: dev
  # 设置上传文件大小
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # 连接池配置
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      #pool-prepared-statements: false
      #max-pool-prepared-statement-per-connection-size: 20
      filters: stat, wall
      validation-query: SELECT 'x'
      aop-patterns: com.*.*.service.*
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin

  # json时间格式设置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:com/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    :banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

# Feign
feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
        loggerLevel: full
  okhttp:
    enabled: true
  httpclient:
    enabled: false
    max-connections: 200
    max-connections-per-route: 50
    time-to-live: 900
    time-to-live-unit: seconds
    connection-timeout: 2000
    follow-redirects: true
    disable-ssl-validation: false

#swagger全局配置
knife4j:
  # 开启增强配置
  enable: true
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username:
    # Basic认证密码
    password: