# 开发环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username:
    password:
    driver-class-name: net.sf.log4jdbc.DriverSpy
#    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr:
        service: ${server.name}
        namespace:
        group:

  redis:
    cluster:
      nodes:
        -
        -
    password:
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
    timeout: 5000

# 日志配置
logging:
  level:
    com: INFO
    jdbc:
      sqltiming: INFO
      connection: ERROR
      resultset: ERROR
      audit: ERROR
      sqlonly: ERROR
      resultsettable: ERROR

file:
  upload:
    dir: ${user.home}/uploadfile


es:
  addr:
  index:
  type:
  userName:
  password:
